### ISSUE TITLE
upload file

### ISSUE THREAD

**Issue by misterfifi1** [golchha21/BoxPHPAPI#13]
the upload files doesn't work for me, the result of put_file is NULL

$box->put_file("test.html","test.html","3884200955");

Could you help me ?

**Comment by misterfifi1** [comment]
Could you give me a functional example ?

**Comment by misterfifi1** [comment]
I found a solution 

/* Uploads a file */
		public function put_file($file, $name, $parent_id) {
			$url = $this->build_url('/files/content', array(), $this->upload_url);
			$attrs = array('name' => $name, 'parent' => array('id' => $parent_id));
			$cfile = new CURLFile(realpath($file),'image/png','pic');
			$params = array('attributes' => json_encode($attrs), 'file' => $cfile);
			return json_decode($this->post($url, $params), true);
		}

**Comment by golchha21** [comment]
There was some changes made in the API hence the upload was not working.
The changes have now been updated to the SDK as well.

**Comment by kwyatt242** [comment]
Hi -
The above solution from misterfifi1 is what fixed my upload issue (continuously getting a null response on upload / 400 error) when using php/curl for the call. Curiously, it would work using the command line. The fix was using 'CURLFile'. Has that been committed yet? I don't see it. ...just hoping this update might help others and save time.

Thanks for the great SDK!

**Comment by misterfifi1** [comment]
I created a pull request but @golchha21 must accept it :) 
Otherwise you can use my fork xD
